### ISSUE TITLE
Witcher 3 invisible characters and creatures

### ISSUE THREAD

**Issue by Thoma5** [acomminos/wine-pba#9]
Tested it on my 970GTX, R7 1700@3.7GHz and pba-2.21 from lutris. 
Since I've not found a correct way to measure fps yet, I can't say anything precise about that, but it feels slightly improved. GPU Utilization went up about 10%, seems much more fluctating now (somewhere between 55 and 80% but usually around 70%). However, all characters and creatures are now invisible.

**Comment by Armored87** [comment]
Recorded a video of Witcher 3 with yesterday's PBA patches, characters still invisible: https://www.youtube.com/watch?v=6U7X_aXWxsI

Wine output log: [log.txt](https://github.com/acomminos/wine-pba/files/1764997/log.txt)

**Comment by mirh** [comment]
I'm kinda sure TW3 got heavily fixed in wine 3.2

**Comment by Thoma5** [comment]
@mirh  I'd appreciate this. However, it has nothing to do with this issue, since this issue is about a regression that is very likely caused by the pba patch.

**Comment by stefson** [comment]
Witcher 3 got even more fixed with wine-3.3, with the old wine-2.21 + staging + the patches from here, performance in fps is worse and characters/creatures are invisible.

**Comment by Armored87** [comment]
@stefson  Are you on Mesa or Nvidia? I'm asking this because in my tests 2.21 + Staging + PBA completely trashes 3.3 + Buffer Patches in terms of performance.

A recent video I recorded using 2.21 + Staging + PBA: https://www.youtube.com/watch?v=6U7X_aXWxsI (showing game running on Ultra)

By comparison 3.3 + Buffer Patches for me it runs at about 27 fps max and at a much lower detail. The frame drops are also more frequent.

**Comment by stefson** [comment]
I'm using an Radeon rx 550 with mesa-17.3.6, llvm-5, kernel 4.14 + amdgpu. With wine-2.21 + staging I have invisible characters just like you in the youtube video, it is not nvidia specific.

**Comment by acomminos** [comment]
Is there another game that can reproduce similar issues? I don't own TW3.

**Comment by mirh** [comment]
It shouldn't bother you too much. 
It was fixed in [3.3](https://bugs.winehq.org/show_bug.cgi?id=43872#c45)

**Comment by Jrugia** [comment]
@mirh Unfortunately not yet, Recent Video 3.3 Staging + PBA: https://www.youtube.com/watch?v=t-FnjIg3JlA  (not recorded by me).

**Comment by stefson** [comment]
Are you using nvidia, just like to guy in the youtube video? #43872 states exactly this, that it may not be fixed for nvidia yet.

**Comment by stefson** [comment]
So, I have to confirm the invisible characters with wine-3.3 + staging + PBA on radeon rx 550 with the amdgpu drivers. But performance is up from 1-2 fps, if at all, to maybe 10. So it points into the right direction :) 

this is the output from the console, with errors and warnings [console.zip](https://github.com/acomminos/wine-pba/files/1785115/console.zip)

If you need some more Informations I can provide them, given that you tell me which commands to use for that in terms of debugging, I'm fairly inexperienced with winedebug.

**Comment by Kerrung** [comment]
I have this issue with PBA in TW3 too. All characters is still invisible with commit 1bc7015.
But I haven't this issue without PBA.

**Comment by acomminos** [comment]
Overwatch had a similar issue, which I addressed in b33e274. If someone could check whether or not that commit fixes TW3, that would be great.

**Comment by strycore** [comment]
A build with the latest commit struggles with TW3. It takes ~30 seconds to get to the intro video (freezing the whole machine) then the video play without issue. Then it also takes another ~30 seconds to get to the game menu. Each timeI tried it, I had to unfocus the Wine window then re-focus it for the main menu to render at all (otherwise the game gets stucks on the last frame of the video). When the game regains focus, it renders frames at super high speed before stabilizing.
I haven't got to the game itself. I seems like it gets stuck on the last frame of the video then my GPU just sits there at 100% utilization (RAM and CPU usage are ok)

**Comment by strycore** [comment]
FWIW, Hellblade had the same issue (invisible character) and it's still present with the latest build (except that now a piece of clothing is rendering)
